version: '2'
services:
 db:
  image: mysql:5.7
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_DATABASE: rails-realworld-example-app
   MYSQL_USER: appuser
   MYSQL_PASSWORD: password
  ports:
   - "3307:3306"
 app:
  build: .
  command: bundle exec rake db:migrate s -p 3000 -b '0.0.0.0'
  volumes: 
   - ".:/var/jenkins_home/workspace/rails-realworld-example-app"
  ports:
   - "3001:3000"
  depends_on:
   - db
  links:
   - db


